### PR TITLE
Add a concrete example of using namespaces

### PR DESCRIPTION
**Pull request by DrRataplan**
And specifically the XSLT-like `xpath-default-namespace` attribute

Lets discuss this before merging, because, technically,w e are deviating from spec a bit here

### CODE REVIEW

**Comment by JoernT** [comment]
which spec you're talking @DrRataplan ?

But anyway - i don't care too much. I'm fine with the xpath-default-namespace approach. 

However regarding the docbook demo - i think we cannot put that instance inline as it's a real xml doc right? Inline docs work for instances without a namspace. They are just HTML DOM (e.g. no empty elements). That instance should be loaded with `src="docbook.xml"`  or so.

We need to have another think about scoping - when a `fx-form` happens to be nested inside another....

**Comment by DrRataplan** [comment]
I was referring to the XForms namespace there. In the #42 discussion, I found out that the XForms 2.0 spec set the default element namespace to 'null'. Without a way to override it.

That `xpath-default-namespace` is inspired by XSLT, and imho a good way to continue.

About the inline xml-in-html, you're totally right. I'll extract that file

**Comment by JoernT** [comment]
@DrRataplan would you mind to change to a real PR - still in Draft mode. Would like to accept that if you don't mind or want to have further changes

**Comment by DrRataplan** [comment]
Pushed a new version where the `bibliography` is in its own file.

**Comment by JoernT** [comment]
key @DrRataplan i tried to integrate this PR by hand but with no luck yet. Get 2 failing tests now. Could you please update the PR based on dev and have a look? Would really like to incorporate the namespace support and the nice example.

**Comment by DrRataplan** [comment]
That's odd. Must be related to those merge conflicts or something. I'll look at it in the afternoon.

**Comment by DrRataplan** [comment]
The commits in this PR build nicely now. Seems it was the refactoring to `fx-fore` from `fx-form` that broke it. CI is now read because `dev` is broken. Working on fixing that right now

**Comment by JoernT** [comment]
yes of course - the failing test - should have flagged that appriately

**Comment by DrRataplan** [comment]
Whew, those were some nasty conflicts. The main issue was that the `xpath` for templates requires namespace bindings in the scope should be working. They did not: therefore the issue. The other operators are evaluated from a different node, which makes them work as expected.

I'd say to integrate this right now and keep our eyes out for other discrepancies. In general, XPaths require a context node, a reference to the containing form (for things like the `index` function), and the node at which the xpath is defined (for namespace bindings). Only when we have them all will XPaths behave like expected.

**Pull request merged**
