### PR TITLE
Implement the fx-var element. VARIABLES!!!

### PR DESCRIPTION
**Pull request by DrRataplan**
This brings variables!

By traversing over the DOM at an early point we get hold of all the variable elements. These are
given to all the 'normal' UI components in a way that they only have access to the preceding
variables. Variables are updated on refresh.

**TODO**

- Unit tests!
- The behaviour for actions
- More examples

Making a draft PR already to show off the progress. Don't integrate yet please

### CODE REVIEW

**Comment by JoernT** [comment]
ah cool - like it. we should maybe add some cases to the demo like using it in model 

```
<fx-var name="foo" value='my_very_long_XPath'>
<fx-var name="bar" value='another_very_long_XPath'>

<fx-bind ref="$foo" required="$bar">
```

**Comment by DrRataplan** [comment]
I updated this PR with some unit tests for variables. It's ready to review. Don;t hesitate to reach out if you have any questions!

**Comment by JoernT** [comment]
that looks very good to me - however we're missing a test for the use of fx-var inside of an action block - maybe even looped one. Code looks like it could work but testcase would be better ;)

**Comment by DrRataplan** [comment]
Hey there! I just added a few tests for exactly that. Turns out I made a few small mistakes earlier, but all's well now!

**Comment by JoernT** [comment]
@DrRataplan hurrah! what a step forward. Will merge asap

**Pull request merged**
