### PR TITLE
Upgrade FontoXPath to 3.26.0

### PR DESCRIPTION
**Pull request by DrRataplan**
Fixes (part of) #111, where all children were listed as dependencies when recalculating a form

### CODE REVIEW

**Comment by JoernT** [comment]
unfortunately i now have 5 faling tests which have to do with detecting references in calcuation graph.... will need examination.

**Comment by DrRataplan** [comment]
That'll teach me from making a PR before running the tests locally :wink: I'll check m out!

**Comment by DrRataplan** [comment]
@JoernT the tests are working now, Turned out that the `getNextSibling` (which was previously used less often) did not track dependencies... It does now!

**Comment by JoernT** [comment]
very cool - thanks @DrRataplan

**Pull request merged**
