### PR TITLE
Fix the XPath used to detect templates

### PR DESCRIPTION
**Pull request by DrRataplan**
And add a unit test to prevent these oopsies in the future

### CODE REVIEW

**Comment by DrRataplan** [comment]
In the submission4 demo I am still getting an outgoing request to `http://localhost:8090/submission2?foo={bar}`, so the version w/o replacements. I think something is missing somewhere, I'll give it a look.

**Comment by DrRataplan** [comment]
Got it. The iron-ajax element that is rendered by in the shadowroot of fx-submission is never getting any new `url` attribute set: only the `fx-submission` element itself gets a new url. This goes deeper.

I'll lay this down for now, hit me up if I can help any further.

**Comment by JoernT** [comment]
found that one already - yep the url attr on the iron-ajax needed updating.
Now facing new problems with constructing the url for that element as it
seems to expect the params to be given as a separate object. Considering to
replace that thingy with the fetch API effectively killing another
dependency.

**Comment by JoernT** [comment]
pushed my latest just in case but it's working now - submission ajax calls
still need fixing - will break on URL params still

**Comment by JoernT** [comment]
@DrRataplan should this be applied or should i await the new PR with the function improvements?

**Comment by DrRataplan** [comment]
This can be integrated (after the conflicts are resolved), but the submission element is still not working perfectly: the requested url is not interpolated correctly. That is awaiting the fetch refactorings.

It does not make it any worse though :sweat_smile:

**Pull request merged**
